### ISSUE TITLE
Art.WebImage.url

### ISSUE THREAD

**Issue by pepebc** [mykle1/MMM-Art#1]
Hi, found this error on Magic Mirror
API key is correct, i can find data directly with that url in the browser, but I get that error in the Magic Mirror module
MMM-Art.js:84 Uncaught TypeError: Cannot read property 'url' of undefined ----> img.src = Art.WebImage.url;

**Comment by mykle1** [comment]
>i can find data directly with that url in the browser,<

The problem is that the image data has been moved outside the response from the GET request. If you know how to retrieve the image under these circumstances then please let me know because I don't. I'm sorry the API from the museum changed the data
